<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bag_manual_synchronizer</name>
  <version>0.1.0</version>
  <description>
    GUI tool to manually synchronize two ROS 2 bags by overlaying their IMU
    signals on ImPlot plots, adjusting a time offset, and saving it to a file.
  </description>
  <maintainer email="michal.pelka@robotec.ai">Michal Pelka</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rosbag2_cpp</depend>
  <depend>rosbag2_storage</depend>
  <depend>sensor_msgs</depend>
  <depend>rcpputils</depend>
  <depend>rosidl_typesupport_introspection_cpp</depend>
  <depend>yaml_cpp_vendor</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
